#!/bin/bash




########################################################
#Author: Abhishek
#Date: 16/04/2001
#This script outputs the node health.
#Version: v1

#######################################################

set -x

df -h


free -g


nproc
